### ISSUE TITLE
error: When I want to fix '이이ㅡㄴ' to '이온' 

### ISSUE THREAD

**Issue by tjwjdgus12** [tjwjdgus12/ChinJiIn#14]
'이온' 의 아래아 -> 'ㅣ' replace 오타에 대해

word_fixer fix 결과

>>> fix('이이ㅡㄴ')
입력한 '이재ㄴ, ㅇㅣㅇㅣㅡ#ㄴ' 는 교정 단어 목록이 존재하지 않습니다.

두가지 부분에서 오류가 나는데
1. cji_converter에서 잘못된 공백이 삽입됩니다.
2. 깨진 한글에 대해 han_converter가 이상하게 작동합니다.

**Comment by redjen8** [comment]
cji_module fixed. can convert '이이ㅡㄴ' well now. check commit 8350d00 on dev branch.

**Comment by redjen8** [comment]
can fix '이이ㅡㄴ' to '이온' now. close this issue.
![이온](https://user-images.githubusercontent.com/13515106/120104488-9fc67680-c18f-11eb-8359-b89b5a316b5f.PNG)
