### ISSUE TITLE
error : recognize number as invalid input

### ISSUE THREAD

**Issue by redjen8** [tjwjdgus12/ChinJiIn#15]
input was '{number}년', this word is already existing in dictionary data, but shows as 'invalid value, in consonant vowel-check' message pops up. 
![8year error](https://user-images.githubusercontent.com/13515106/120103806-65a7a580-c18c-11eb-82b7-39131f7e870b.PNG)

**Comment by tjwjdgus12** [comment]
It is because some data like '1년', '2년', ... exist in optimized_dict. @kindkiz

**Comment by selgyun** [comment]
Deleted data containing numbers like '1년', '2년'. Now we can only check '년', but we still have an invalid value problem. @SuperChobo 
Input: '2년'
![image](https://user-images.githubusercontent.com/29320054/120151679-8244eb80-c227-11eb-933b-189940e7ba97.png)

**Comment by SuperChobo** [comment]
it was because of number, and I fixed it. So now, there will not be 'invalid value' message.

**Comment by tjwjdgus12** [comment]
now solved.
