### ISSUE TITLE
Error in Making Hangeul string from Cheonjiin string

### ISSUE THREAD

**Issue by ChangminYi** [tjwjdgus12/ChinJiIn#2]
hangeul_convert.py에서 'ㄸ' 이 리스트에 없다고 에러가 발생합니다.
![버그1](https://user-images.githubusercontent.com/30003205/117942748-5e883700-b346-11eb-9057-014f5ec3d91c.png)

**Comment by selgyun** [comment]
'ㅉ'도 인식이 안됨을 발견했습니다.
![image](https://user-images.githubusercontent.com/29320054/117952013-b6776b80-b34f-11eb-8ba9-723581640a5a.png)
