### ISSUE TITLE
error : found space letter '#' included in word fix suggestions

### ISSUE THREAD

**Issue by redjen8** [tjwjdgus12/ChinJiIn#20]
Input was '아이', found a result that contains space letter '#'.
![space](https://user-images.githubusercontent.com/13515106/120275414-3ad46300-c2ec-11eb-9e55-b9bd47652f40.PNG)

**Comment by ChangminYi** [comment]
Found one more error case, Input was '낭아지'
![image](https://user-images.githubusercontent.com/30003205/120277365-ef6f8400-c2ee-11eb-98ea-1436a0862eb9.png)

**Comment by tjwjdgus12** [comment]
I checked it was fixed
