### ISSUE TITLE
'ᆢ' convert issue

### ISSUE THREAD

**Issue by tjwjdgus12** [tjwjdgus12/ChinJiIn#25]
![image](https://user-images.githubusercontent.com/29909359/120883233-f6600480-c616-11eb-852f-b8d1eb46a6c3.png)
![image](https://user-images.githubusercontent.com/29909359/120883238-ff50d600-c616-11eb-8ab0-93298b0fee69.png)

@redjen8 Can you fix it on cji_converter? ( ᆢ -> ᆞᆞ)

**Comment by redjen8** [comment]
now solved. close this issue.
