### ISSUE TITLE
can't fix '강ㅅ우성' to '감수성'

### ISSUE THREAD

**Issue by tjwjdgus12** [tjwjdgus12/ChinJiIn#7]
'강ㅅ우성' is 'ㄱㅣᆞㅇㅅㅇㅡᆞㅅᆞㅣㅇ'
'감수성' is 'ㄱㅣᆞㅇㅇㅅㅡᆞㅅᆞㅣㅇ'

It's edit distance is 1 ('ㅇ' and 'ㅅ' transposed), but it is not fixed.

**Comment by ChangminYi** [comment]
![버그 되려다 만 것](https://user-images.githubusercontent.com/30003205/118385258-8d552480-b648-11eb-9631-6a271b221c58.png)
내 환경에서는 잘 돌아감.
